app:
  chrome-config:
    web-driver-location: 'C:\\finances\\chromedriver.exe'
    web-driver-download-file: 'C:\\Users\\sgayd\\Downloads\\transactions.csv'
    web-driver-headless: false
  mint-config:
    login-page: 'https://mint.intuit.com/'
    transaction-download-link: 'https://mint.intuit.com/transactionDownload.event?queryNew=&offset=0&filterType=cash&comparableType=8'

---

spring:
  profiles: dev
app:
  chrome-config:
    wait-for-update-seconds: 60

---

spring:
  profiles: prod
app:
  chrome-config:
    wait-for-update-seconds: 90

#isFinancesAppRunningLocallyAllInSpringBoot -- search for this and set to true for local, false for deploy